# Valeurs par defaut du role ntfy
# Peuvent etre surchargees dans host_vars/<machine>.yml

ntfy_version: "2.11.0"  # source de verite : inventory/group_vars/all/versions.yml
ntfy_image: "binwiederhier/ntfy"
ntfy_domain: "ntfy.{{ base_domain }}"
ntfy_network_name: "ntfy-net"
ntfy_port: 80
ntfy_data_dir: "/opt/modules/ntfy"

# UID/GID du user ntfy dans le container
# L'image binwiederhier/ntfy tourne en UID 1000 par defaut
ntfy_container_uid: 1000
ntfy_container_gid: 1000
