---
- name: Reload Docker Stack Pi
  shell: "cd {{ pi_stack_dir }} && docker compose up -d --remove-orphans"

- name: Restart AdGuard
  shell: "cd {{ pi_stack_dir }} && docker compose restart adguard"
